### PR TITLE
vhost_user: Add Inflight I/O tracking support

### LINKED ISSUE #43: Add support for Inflight I/O tracking
The vhost-user implementation is missing the Inflight I/O tracking feature in order to recover fully from a backend crash or restart while the VM/guest is running.

### PR DESCRIPTION
**Pull request by sboeuf**
The inflight I/O tracking feature is useful for handling crashes and
disconnections from the backend. It allows the backend to rely on a
buffer that was shared earlier with the VMM to restore to the previous
state it was before the crash.

This feature depends on the availability of the protocol feature
VHOST_USER_PROTOCOL_F_INFLIGHT_SHMFD, and it implements both
VHOST_USER_GET_INFLIGHT_FD and VHOST_USER_SET_INFLIGHT_FD messages.

Fixes #43

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
@zhangjaycee 
>Great! I will do some tests with some vhost-user backends that support inflight tracking later, I will give feedback if there is any problem with this PR.

Sounds awesome! :)

**Comment by sboeuf** [comment]
@jiangliu looks like the buildkite CI is blocked, any idea what's wrong?

**Comment by sboeuf** [comment]
@zhangjaycee just wanted to let you know I added a small fix to the PR. So please make sure you rely on the latest version when doing your testing.

**Comment by sboeuf** [comment]
@jiangliu @rbradford PTAL

File: src/vhost_user/master.rs [hunk 1]
```diff
@@ -51,6 +51,12 @@ pub trait VhostUserMaster: VhostBackend {
     /// Setup slave communication channel.
     fn set_slave_request_fd(&mut self, fd: RawFd) -> Result<()>;
 
+    /// Retrieve shared buffer for inflight I/O tracking.
```
Comment (jiangliu) [inline src/vhost_user/master.rs:54]: Could you please help to add doc to state the ownership of `fd` will be transferred to the caller. Or should return an File object instead?

File: src/vhost_user/master.rs [hunk 2]
```diff
@@ -452,6 +458,43 @@ impl VhostUserMaster for Master {
...
+            return error_code(VhostUserError::InvalidOperation);
+        }
+
+        let hdr = node.send_request_header(MasterReq::GET_INFLIGHT_FD, None)?;
+        let (inflight, fds) = node.recv_reply_with_fds::<VhostUserInflight>(&hdr)?;
+
+        if let Some(fds) = fds {
+            if fds.len() == 1 {
+                return Ok((inflight, fds[0]));
+            }
```
Comment (jiangliu) [inline src/vhost_user/master.rs:473]: Should close the received fds to avoid fd leakage.

File: src/vhost_user/master.rs [hunk 3]
```diff
@@ -452,6 +458,43 @@ impl VhostUserMaster for Master {
...
+    }
+
+    fn set_inflight_fd(&mut self, inflight: &VhostUserInflight, fd: RawFd) -> Result<()> {
+        let mut node = self.node();
+        if node.acked_protocol_features & VhostUserProtocolFeatures::INFLIGHT_SHMFD.bits() == 0 {
+            return error_code(VhostUserError::InvalidOperation);
+        }
+
+        if inflight.mmap_size == 0
+            || inflight.mmap_offset >= inflight.mmap_size
```
Comment (jiangliu) [inline src/vhost_user/master.rs:486]: We should not check mmap_offset >= mmap_size, according to the spec:
```
mmap size: a 64-bit size of area to track inflight I/O
mmap offset: a 64-bit offset of this area from the start of the supplied file descriptor
```

File: src/vhost_user/message.rs [hunk 4]
```diff
@@ -673,6 +673,46 @@ impl VhostUserMsgValidator for VhostUserConfig {
...
+            num_queues,
+            queue_size,
+        }
+    }
+}
+
+impl VhostUserMsgValidator for VhostUserInflight {
+    fn is_valid(&self) -> bool {
+        if self.mmap_size == 0
+            || self.mmap_offset >= self.mmap_size
```
Comment (jiangliu) [inline src/vhost_user/message.rs:706]: we should not check `self.mmap_offset >= self.mmap_size` here too.

File: src/vhost_user/slave_req_handler.rs [hunk 5]
```diff
@@ -62,6 +62,8 @@ pub trait VhostUserSlaveReqHandler {
     fn get_config(&self, offset: u32, size: u32, flags: VhostUserConfigFlags) -> Result<Vec<u8>>;
     fn set_config(&self, offset: u32, buf: &[u8], flags: VhostUserConfigFlags) -> Result<()>;
     fn set_slave_req_fd(&self, _vu_req: SlaveFsCacheReq) {}
+    fn get_inflight_fd(&self) -> Result<(VhostUserInflight, RawFd)>;
+    fn set_inflight_fd(&self, inflight: &VhostUserInflight, fd: RawFd) -> Result<()>;
```
Comment (jiangliu) [inline src/vhost_user/slave_req_handler.rs:66]: replace `fd: RawFd` with `file: File`?

File: src/vhost_user/slave_req_handler.rs [hunk 6]
```diff
@@ -435,6 +447,38 @@ impl<S: VhostUserSlaveReqHandler> SlaveReqHandler<S> {
...
+                    .send_message(&reply_hdr, &inflight, Some(&[fd]))?;
+            }
+            MasterReq::SET_INFLIGHT_FD => {
+                if self.acked_protocol_features & VhostUserProtocolFeatures::INFLIGHT_SHMFD.bits()
+                    == 0
+                {
+                    return Err(Error::InvalidOperation);
+                }
+                let fd = if let Some(fds) = &rfds {
+                    if fds.len() != 1 {
```
Comment (jiangliu) [inline src/vhost_user/slave_req_handler.rs:470]: We should close `fds` here too.

File: src/vhost_user/master.rs [hunk 7]
```diff
@@ -452,6 +458,43 @@ impl VhostUserMaster for Master {
         Ok(())
     }
 
+    fn get_inflight_fd(&mut self) -> Result<(VhostUserInflight, RawFd)> {
+        let mut node = self.node();
+        if node.acked_protocol_features & VhostUserProtocolFeatures::INFLIGHT_SHMFD.bits() == 0 {
+            return error_code(VhostUserError::InvalidOperation);
+        }
+
+        let hdr = node.send_request_header(MasterReq::GET_INFLIGHT_FD, None)?;
```
Comment (zhangjaycee) [inline src/vhost_user/master.rs:467]: According to the C implementation of libvhost-user, the backend also needs the `VhostUserInflight` to create a memfd and mmap it with proper size.  When I perform testing, with QEMU's vhost-user-blk daemon, this absence of msg payload will cause the daemon to panic (see https://github.com/qemu/qemu/blob/7fe7fae8b48e3f9c647fd685e5155ebc8e6fb84d/subprojects/libvhost-user/libvhost-user.c#L1662).

Therefore, maybe we should create a `VhostUserInflight` and send it along with the header. (Reference from QEMU: https://github.com/qemu/qemu/blob/7fe7fae8b48e3f9c647fd685e5155ebc8e6fb84d/hw/virtio/vhost-user.c#L2305)

File: src/vhost_user/master.rs (hunk 1 above)
Comment (sboeuf) [reply src/vhost_user/master.rs:54]: I'm gonna follow your suggestion of putting this into a `File`, this way the ownership is obvious.

File: src/vhost_user/master.rs (hunk 2 above)
Comment (sboeuf) [reply src/vhost_user/master.rs:473]: Yes I'll fix that

File: src/vhost_user/master.rs (hunk 3 above)
Comment (sboeuf) [reply src/vhost_user/master.rs:486]: You're right, I misread the spec, the mmap offset relates to the fd.

File: src/vhost_user/message.rs (hunk 4 above)
Comment (sboeuf) [reply src/vhost_user/message.rs:706]: I'll fix it.

File: src/vhost_user/slave_req_handler.rs (hunk 5 above)
Comment (sboeuf) [reply src/vhost_user/slave_req_handler.rs:66]: Yes

File: src/vhost_user/slave_req_handler.rs (hunk 6 above)
Comment (sboeuf) [reply src/vhost_user/slave_req_handler.rs:470]: Agreed.

File: src/vhost_user/master.rs (hunk 7 above)
Comment (sboeuf) [reply src/vhost_user/master.rs:467]: Yes let me fix that :)

**Comment by sboeuf** [comment]
@jiangliu @zhangjaycee I addressed all your comments, please have a look!

**Review by jiangliu — APPROVED** [review]

**Comment by sboeuf** [comment]
@zhangjaycee could you confirm the latest version of this PR works for you?

**Review by sameo — APPROVED** [review]

**Comment by zhangjaycee** [comment]
> @zhangjaycee could you confirm the latest version of this PR works for you?

Hi, I just modified the vhost-user-blk device of cloud-hypervisor to use the two inflight interfaces, ran fio on the vhost-user-blk device in guest, and the fio worked fine after reconnection, no I/O hang happened.

Soon, I will send out the modification as a PR to the cloud-hypervisor repo.

**Comment by sboeuf** [comment]
@zhangjaycee 
>Hi, I just modified the vhost-user-blk device of cloud-hypervisor to use the two inflight interfaces, ran fio on the vhost-user-blk device in guest, and the fio worked fine after reconnection, no I/O hang happened.
Soon, I will send out the modification as a PR to the cloud-hypervisor repo.

Awesome! :smile:

**Comment by zhangjaycee** [comment]
> > @zhangjaycee could you confirm the latest version of this PR works for you?
> 
> Hi, I just modified the vhost-user-blk device of cloud-hypervisor to use the two inflight interfaces, ran fio on the vhost-user-blk device in guest, and the fio worked fine after reconnection, no I/O hang happened.
> 
> Soon, I will send out the modification as a PR to the cloud-hypervisor repo.

The cloud-hypervisor PR: https://github.com/cloud-hypervisor/cloud-hypervisor/pull/2749
