### PR TITLE
Fix feature unification issues with gpu-socket feature

### LINKED ISSUE #265: gpu-socket feature causing feature unification issues
since the set_gpu_socket feature is behind a feature flag, this cause feature unification issues, because vhost-device-gpu is enabling that feature and other crates are not enabling it. According to rust feature reference: 

> That is, enabling a feature should not disable functionality, and it should usually be safe to enable any combination of features. A feature should not introduce a [SemVer-incompatible change](https://doc.rust-lang.org/cargo/reference/features.html#semver-compatibility).

### PR DESCRIPTION
**Pull request by dorindabassey**
### Summary of the PR

make `set_gpu_socket` method a default implementation and remove conditional compilation because cargo feature unification already defeats the purpose of the `gpu-socket` feature flag.

Fixes #265 

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR have Signed-Off-By trailers (with
  `git commit -s`), and the commit message has max 60 characters for the
  summary and max 75 characters for each description line.
- [x] All added/changed functionality has a corresponding unit/integration
  test.
- [x] All added/changed public-facing functionality has entries in the "Upcoming 
  Release" section of CHANGELOG.md (if no such section exists, please create one).
- [x] Any newly added `unsafe` code is properly documented.

### CODE REVIEW

**Comment by stefano-garzarella** [comment]
>     * [x]  All added/changed public-facing functionality has entries in the "Upcoming
>       Release" section of CHANGELOG.md (if no such section exists, please create one).

You flagged this, but I don't see the entry in the changelogs, can you please add it?

**Comment by dorindabassey** [comment]
> You flagged this, but I don't see the entry in the changelogs, can you please add it?

My bad! I will add it in the next update.

File: vhost-user-backend/src/backend.rs [hunk 1]
```diff
@@ -89,9 +89,9 @@ pub trait VhostUserBackend: Send + Sync {
     /// Set handler for communicating with the frontend by the gpu specific backend communication
     /// channel.
     ///
-    /// This method only exits when the crate feature gpu-socket is enabled, because this is only
-    /// useful for a gpu device.
-    fn set_gpu_socket(&self, _gpu_backend: GpuBackend);
+    /// A default implementation is provided as we cannot expect all backends to implement this
+    /// function.
+    fn set_gpu_socket(&self, _gpu_backend: GpuBackend) {}
```
[the remark this answers is not in the document]
Comment (dorindabassey) [reply vhost-user-backend/src/backend.rs:94]: Make sense, I will let this return an error then.

[the remark this answers is not in the document]
Comment (dorindabassey) [reply vhost-user-backend/src/backend.rs]: wdyt, Is it better this way?

File: vhost-user-backend/src/backend.rs [hunk 2]
```diff
@@ -89,9 +89,14 @@ pub trait VhostUserBackend: Send + Sync {
...
     ///
-    /// This method only exits when the crate feature gpu-socket is enabled, because this is only
-    /// useful for a gpu device.
-    fn set_gpu_socket(&self, _gpu_backend: GpuBackend);
+    /// This function return a `Result`, returning an error if the backend does not implement this
+    /// function.
+    fn set_gpu_socket(&self, _gpu_backend: GpuBackend) -> Result<()> {
+        Err(std::io::Error::new(
+            std::io::ErrorKind::Unsupported,
+            "back end requires set_gpu_socket to be implemented",
```
Comment (stefano-garzarella) [inline vhost-user-backend/src/backend.rs:97]: I'd follow `check_device_state()`, so something like `back end does not support gpu socket`.

**Review by stefano-garzarella — COMMENTED** [review]
```
make set_gpu_socket a required implementation

change the requirement of the trait when implementing
the `set_gpu_socket` method, thereby ensuring the
backend implements the `set_gpu_socket` only if the
frontend expects it.
```
This commit title/ description is not clear to me. Not sure if it's old, but it looks like we are doing the opposite, providing a default implementation.

File: vhost-user-backend/src/backend.rs [hunk 3]
```diff
@@ -89,9 +89,16 @@ pub trait VhostUserBackend: Send + Sync {
     /// Set handler for communicating with the frontend by the gpu specific backend communication
     /// channel.
     ///
-    /// This method only exits when the crate feature gpu-socket is enabled, because this is only
-    /// useful for a gpu device.
-    fn set_gpu_socket(&self, _gpu_backend: GpuBackend);
+    /// This function returns a `Result`, returning an error if the backend does not implement this
+    /// function.
+    /// A default implementation is provided as we cannot expect all backends to implement this
+    /// function.
```
Comment (stefano-garzarella) [inline vhost-user-backend/src/backend.rs:95]: nit: I'd remove these 2 lines, I don't see much more value after the lines above,

**Review by stefano-garzarella — COMMENTED** [review]
Please try to take more care about commit title/description:
- in patch 1 I'd add a link to https://doc.rust-lang.org/cargo/reference/features.html#feature-unification and also to the issue #265 
- in patch 2 I don't understand this: `and ensure that the backend implements
the set_gpu_socket only if the frontend expects it.` How we are doing it?

**Comment by dorindabassey** [comment]
> Please try to take more care about commit title/description:

ok sure, noted.
 
>     * in patch 2 I don't understand this: `and ensure that the backend implements the set_gpu_socket only if the frontend expects it.` How we are doing it?

maybe it's not clear, but i was referring to error we now return. in https://github.com/rust-vmm/vhost/blob/5c1154407a67e46f3b55b9ab6e006b7717952d0b/vhost-user-backend/src/backend.rs#L96C1-L101C6

**Review by stefano-garzarella — DISMISSED** [review]
@dorindabassey thanks for fixing the commit message, now it's clear.

**Comment by stefano-garzarella** [comment]
Should we release `vhost-v0.12.1` and `vhost-user-backend-v0.16.1` with this fix?
I guess no one was using that feature, so not sure if we need to yank the 2 previous versions.

**Comment by dorindabassey** [comment]
> Should we release `vhost-v0.12.1` and `vhost-user-backend-v0.16.1` with this fix? I guess no one was using that feature, so not sure if we need to yank the 2 previous versions.

Yeah, I agree. It makes sense to make a new release. I think the 2 previous versions can stay since it was only vhost-device-gpu that was using that feature.

File: vhost-user-backend/src/backend.rs [hunk 4]
```diff
@@ -205,13 +208,17 @@ pub trait VhostUserBackendMut: Send + Sync {
...
     ///
-    /// This method only exits when the crate feature gpu-socket is enabled, because this is only
-    /// useful for a gpu device.
-    fn set_gpu_socket(&mut self, gpu_backend: GpuBackend);
+    /// This function returns a `Result`, returning an error if the backend does not implement this
+    /// function.
+    fn set_gpu_socket(&mut self, _gpu_backend: GpuBackend) -> Result<()> {
+        Err(std::io::Error::new(
+            std::io::ErrorKind::Unsupported,
+            "back end does not support gpu socket",
```
Comment (epilys) [inline vhost-user-backend/src/backend.rs:219]: Small nit (`back end` -> `backend` and extra info)

```suggestion
            "Backend does not support set_gpu_socket() / VHOST_USER_GPU_SET_SOCKET",
```

File: vhost-user-backend/src/backend.rs [hunk 5]
```diff
@@ -610,8 +614,9 @@ pub mod tests {
 
         fn set_backend_req_fd(&mut self, _backend: Backend) {}
 
-        #[cfg(feature = "gpu-socket")]
-        fn set_gpu_socket(&mut self, _gpu_backend: GpuBackend) {}
+        fn set_gpu_socket(&mut self, _gpu_backend: GpuBackend) -> Result<()> {
```
Comment (epilys) [inline vhost-user-backend/src/backend.rs:617]: Shouldn't this better be removed since there's a default impl?

File: vhost-user-backend/tests/vhost-user-server.rs [hunk 6]
```diff
@@ -79,8 +78,9 @@ impl VhostUserBackendMut for MockVhostBackend {
         Ok(())
     }
 
-    #[cfg(feature = "gpu-socket")]
-    fn set_gpu_socket(&mut self, _gpu_backend: GpuBackend) {}
+    fn set_gpu_socket(&mut self, _gpu_backend: GpuBackend) -> Result<()> {
+        Ok(())
+    }
```
Comment (epilys) [inline vhost-user-backend/tests/vhost-user-server.rs:83]: Same as prior comment

File: vhost/src/vhost_user/backend_req_handler.rs [hunk 7]
```diff
@@ -241,9 +238,8 @@ impl<T: VhostUserBackendReqHandlerMut> VhostUserBackendReqHandler for Mutex<T> {
         self.lock().unwrap().set_backend_req_fd(backend)
     }
 
-    #[cfg(feature = "gpu-socket")]
     fn set_gpu_socket(&self, gpu_backend: GpuBackend) {
-        self.lock().unwrap().set_gpu_socket(gpu_backend);
+        self.lock().unwrap().set_gpu_socket(gpu_backend)
```
[the remark this answers is not in the document]
Comment (epilys) [reply vhost/src/vhost_user/backend_req_handler.rs:242]: Ok now that it returns `Result` this review comment can be resolved

File: vhost/src/vhost_user/dummy_backend.rs [hunk 8]
```diff
@@ -259,8 +259,9 @@ impl VhostUserBackendReqHandlerMut for DummyBackendReqHandler {
         Ok(())
     }
 
-    #[cfg(feature = "gpu-socket")]
-    fn set_gpu_socket(&mut self, _gpu_backend: GpuBackend) {}
+    fn set_gpu_socket(&mut self, _gpu_backend: GpuBackend) -> Result<()> {
+        Ok(())
+    }
```
Comment (epilys) [inline vhost/src/vhost_user/dummy_backend.rs:264]: Let's remove this

**Review by epilys — APPROVED** [review]
Left a few very minor comments but otherwise LGTM for merging

**Review by epilys — CHANGES_REQUESTED** [review]
Left a few very minor comments but otherwise LGTM for merging

File: vhost-user-backend/src/backend.rs (hunk 4 above)
Comment (stefano-garzarella) [reply vhost-user-backend/src/backend.rs:219]: I don't know why, but other messages are using `back end` so I suggested continuing in that direction, but I also prefer `backend`.

File: vhost-user-backend/src/backend.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (stefano-garzarella) [reply vhost-user-backend/src/backend.rs]: > @stefano-garzarella Error or panic? Should the back-end remain operational after being sent invalid commands? 🤔

I saw this comment by email, but I spent 2 min to find it (GH gui is bad).
I think a malicious driver shouldn't crash a device, so I'd avoid panic as much as possible.

**Review by stefano-garzarella — APPROVED** [review]

File: vhost-user-backend/src/backend.rs [hunk 9]
```diff
@@ -87,13 +86,17 @@ pub trait VhostUserBackend: Send + Sync {
...
     ///
-    /// This method only exits when the crate feature gpu-socket is enabled, because this is only
-    /// useful for a gpu device.
-    fn set_gpu_socket(&self, _gpu_backend: GpuBackend);
+    /// This function returns a `Result`, returning an error if the backend does not implement this
+    /// function.
+    fn set_gpu_socket(&self, _gpu_backend: GpuBackend) -> Result<()> {
+        Err(std::io::Error::new(
+            std::io::ErrorKind::Unsupported,
+            "back end does not support set_gpu_socket() / VHOST_USER_GPU_SET_SOCKET",
```
Comment (epilys) [inline vhost-user-backend/src/backend.rs:97]:
```suggestion
            "backend does not support set_gpu_socket() / VHOST_USER_GPU_SET_SOCKET",
```

File: vhost-user-backend/src/backend.rs [hunk 10]
```diff
@@ -205,13 +208,17 @@ pub trait VhostUserBackendMut: Send + Sync {
...
     ///
-    /// This method only exits when the crate feature gpu-socket is enabled, because this is only
-    /// useful for a gpu device.
-    fn set_gpu_socket(&mut self, gpu_backend: GpuBackend);
+    /// This function returns a `Result`, returning an error if the backend does not implement this
+    /// function.
+    fn set_gpu_socket(&mut self, _gpu_backend: GpuBackend) -> Result<()> {
+        Err(std::io::Error::new(
+            std::io::ErrorKind::Unsupported,
+            "back end does not support set_gpu_socket() / VHOST_USER_GPU_SET_SOCKET",
```
Comment (epilys) [inline vhost-user-backend/src/backend.rs:219]:
```suggestion
            "backend does not support set_gpu_socket() / VHOST_USER_GPU_SET_SOCKET",
```

**Review by epilys — CHANGES_REQUESTED** [review]

File: vhost-user-backend/src/backend.rs (hunk 9 above)
Comment (stefano-garzarella) [reply vhost-user-backend/src/backend.rs:97]: In `vhost-user-backend/src/backend.rs` all other error messages already use `back end`. I don't know why, and I also prefer `backend`, but for consistently I'd suggest staying with `back end` for now. I can send another PR later to fix all of them. WDYT?

Comment (TimePrinciple) [reply vhost-user-backend/src/backend.rs:97]: > In `vhost-user-backend/src/backend.rs` all other error messages already use `back end`. I don't know why, and I also prefer `backend`, but for consistently I'd suggest staying with `back end` for now. I can send another PR later to fix all of them. WDYT?

🫨 I can help there, if you are willing to delegate to me

Comment (epilys) [reply vhost-user-backend/src/backend.rs:97]: > In `vhost-user-backend/src/backend.rs` all other error messages already use `back end`. I don't know why, and I also prefer `backend`, but for consistently I'd suggest staying with `back end` for now. I can send another PR later to fix all of them. WDYT?

I agree, personally I don't like adding unorthodox spellings for consistency even if they are to be fixed later. I realise this is really unimportant and I'm holding the PR up for this 🥺 I thought it'd be easy to fix by dorinda though (I'd do it myself but I can't push at her repo).

It's not fixed yet so I will change my review to approval and not changes requested. I wouldn't want to inconvenience for minutiae!

**Review by epilys — APPROVED** [review]

File: vhost-user-backend/src/backend.rs (hunk 9 above)
Comment (stefano-garzarella) [reply vhost-user-backend/src/backend.rs:97]: > I agree, personally I don't like adding unorthodox spellings for consistency even if they are to be fixed later.

Yep, this is a good point.

>I realise this is really unimportant and I'm holding the PR up for this 🥺 I thought it'd be easy to fix by dorinda though (I'd do it myself but I can't push at her repo).

@dorindabassey up to you if you want to fix it now, or we can fix later, but I agree that we can replace "back end" with "backend". @TimePrinciple if you have time, feel free to check that, maybe also for the frontend.

Comment (dorindabassey) [reply vhost-user-backend/src/backend.rs:97]: @stefano-garzarella I don't mind, I can fix it in this PR.

**Review by stefano-garzarella — APPROVED** [review]

**Comment by stefano-garzarella** [comment]
@Ablu @germag if you have time, can you take a look?

> Should we release `vhost-v0.12.1` and `vhost-user-backend-v0.16.1` with this fix? I guess no one was using that feature, so not sure if we need to yank the 2 previous versions.

also, WDYT about this?

**Review by epilys — APPROVED** [review]
Thanks for your patience @dorindabassey, haha :)

**Comment by stefano-garzarella** [comment]
> Thanks for your patience @dorindabassey, haha :)

haha, but also @epilys thanks for spending time helping to review this PR! Really appreciated!

**Comment by Ablu** [comment]
> > Should we release `vhost-v0.12.1` and `vhost-user-backend-v0.16.1` with this fix? I guess no one was using that feature, so not sure if we need to yank the 2 previous versions.
> 
> also, WDYT about this?

No opinion on this. But yes, seems to warrant a yank. Feel free to do whatever you think makes sense :)
